---
- hosts: all
  gather_facts: no
  tasks:

  - name: importing precheck job 
    import_tasks: precheck_job.yaml


  - name: Ansible remove existing var file
    file:
#      path: ./var_file/success_report.txt
      paths: "/var/lib/awx/projects/_22__storage_new/var_file/success_report.txt"
      state: absent
    no_log: True
    ignore_errors: yes

  - name: Ansible delete file
    find:
#      paths: "./var_file/"
      paths: "/var/lib/awx/projects/_22__storage_new/var_file/"
      patterns: "*.yaml"
    register: files_to_delete
    no_log: True

  - name: Ansible remove existing var file
    file:
      path: "{{ item.path }}"
      state: absent
    with_items: "{{ files_to_delete.files }}"
    no_log: True

  - name: Run a script
    script: ./scripts/start_job.sh
    register: test
#    no_log: True
#
  - name: Run a script
    script: ./scripts/email_success_report.sh
    register: test
#    no_log: True

