---
- hosts: localhost
  connection: local
  gather_facts: no
  vars_files: "{{ myvarfile }}"
  tasks:
  - name: Getting detail-info of specific storage group
    block:
      - name: Getting detail-info of specific storage group
        uri:
          url: "{{ unisphere_url }}/univmax/restapi/90/sloprovisioning/symmetrix/{{ symmetrixId }}/storagegroup/{{ storageGroupId }}"
          method: GET
          validate_certs: no
          user: "{{ Username }}"
          password: "{{ Password }}"
          force_basic_auth: yes
          status_code: 201,200
        register: storage_group_details
      - debug:
          msg: "{{ storage_group_details }}"
    rescue:
      - debug:
          msg: 'I caught an error'
      - shell: echo -e "Hi Team  \n\nTask- Getting detail-info of specific storage group- FAILED\n\nRegards" | mailx  -s "Update on ticket {{ Ticket }}" -S smtp="{{ smtp_server }}" "{{ email_id }}"
      - meta: end_play
  - name: volume creation for an storage group
    block:
      - name: volume creation for an storage group
        uri:
          url: "{{ unisphere_url }}/univmax/restapi/90/sloprovisioning/symmetrix/{{ symmetrixId }}/storagegroup/{{ storageGroupId }}"
          method: PUT
          validate_certs: no
          user: "{{ Username }}"
          password: "{{ Password }}"
          force_basic_auth: yes
          status_code: 201,200
          body_format: json
          body:
            {
            "editStorageGroupActionParam": {
            "expandStorageGroupParam": {
            "addVolumeParam": {
            "num_of_vols": "{{ extension_volume_count }}",
            "volumeIdentifier": {
            "identifier_name": "{{ Ticket }}",
            "volumeIdentifierChoice": "identifier_name"
            },
            "volumeAttribute": {
            "volume_size": "{{ extension_volume_size}}",
            "capacityUnit": "GB"
            }
            }
            }
            }
            }
        register: volume_extension
      - debug:
          msg: "{{ volume_extension }}"
    rescue:
      - debug:
          msg: 'I caught an error'
      - shell: echo -e "Hi Team  \n\nTask- Volume creation for an storage group- FAILED \n\nRegards" | mailx  -s "Update on ticket {{ Ticket }}" -S smtp="{{ smtp_server }}" "{{ email_id }}"
      - meta: end_play
  - name: Getting the device details information of storage group
    block:
      - name: Getting the device details information of storage group
        uri:
          url: "{{ unisphere_url }}/univmax/restapi/90/sloprovisioning/symmetrix/{{ symmetrixId }}/volume?volume_identifier={{ Ticket }}&storageGroupId={{ storageGroupId }}"
          method: GET
          validate_certs: no
          user: "{{ Username }}"
          password: "{{ Password }}"
          force_basic_auth: yes
          status_code: 201,200
        register: volume_details
      - name: list of wwn
        debug:
          msg: "{{ volume_details.json.resultList.result|map(attribute='volumeId')|list }}"
    rescue:
      - debug:
          msg: 'I caught an error'
      - shell: echo -e "Hi Team  \n\nTask- Getting the device details information of storage group- FAILED \n\nRegards" | mailx  -s "Update on ticket {{ Ticket }}" -S smtp="{{ smtp_server }}" "{{ email_id }}"
      - meta: end_play
  - debug:
      msg: "Request - {{Ticket}} has been completed successfully"

