---
- hosts: localhost
  gather_facts: yes
  tasks:
  - debug:
      msg: "Value: {{ ansible_local.playbook_vars.unisphere_url }}"
  - name: Getting detail-info of specific storage group
    block:
      - name: Getting detail-info of specific storage group
        uri:
          url: "{{ ansible_local.playbook_vars.unisphere_url }}/univmax/restapi/90/sloprovisioning/symmetrix/{{ ansible_local.playbook_vars.symmetrixId }}/storagegroup/{{ ansible_local.playbook_vars.storageGroupId }}"
          method: GET
          validate_certs: no
          user: "{{ ansible_local.playbook_vars.Username }}"
          password: "{{ ansible_local.playbook_vars.Password }}"
          force_basic_auth: yes
          status_code: 201,200
        register: storage_group_details
      - debug:
          msg: "{{ storage_group_details }}"
    rescue:
      - debug:
          msg: 'I caught an error'
      - shell: echo -e "Hi Team  \n\nTask- Getting detail-info of specific storage group- FAILED\n\nRegards" | mailx  -s "Update on ticket {{ ansible_local.playbook_vars.Ticket }}" -S smtp="{{ ansible_local.playbook_vars.smtp_server }}" "{{ ansible_local.playbook_vars.email_id }}"
      - meta: end_play
  - name: volume creation for an storage group
    block:
      - name: volume creation for an storage group
        uri:
          url: "{{ ansible_local.playbook_vars.unisphere_url }}/univmax/restapi/90/sloprovisioning/symmetrix/{{ ansible_local.playbook_vars.symmetrixId }}/storagegroup/{{ ansible_local.playbook_vars.storageGroupId }}"
          method: PUT
          validate_certs: no
          user: "{{ ansible_local.playbook_vars.Username }}"
          password: "{{ ansible_local.playbook_vars.Password }}"
          force_basic_auth: yes
          status_code: 201,200
          body_format: json
          body:
            {
            "editStorageGroupActionParam": {
            "expandStorageGroupParam": {
            "addVolumeParam": {
            "num_of_vols": "{{ ansible_local.playbook_vars.extension_volume_count }}",
            "volumeIdentifier": {
            "identifier_name": "{{ ansible_local.playbook_vars.Ticket }}",
            "volumeIdentifierChoice": "identifier_name"
            },
            "volumeAttribute": {
            "volume_size": "{{ ansible_local.playbook_vars.extension_volume_size}}",
            "capacityUnit": "GB"
            }
            }
            }
            }
            }
        register: volume_extension
      - debug:
          msg: "{{ volume_extension }}"
    rescue:
      - debug:
          msg: 'I caught an error'
      - shell: echo -e "Hi Team  \n\nTask- Volume creation for an storage group- FAILED \n\nRegards" | mailx  -s "Update on ticket {{ ansible_local.playbook_vars.Ticket }}" -S smtp="{{ ansible_local.playbook_vars.smtp_server }}" "{{ ansible_local.playbook_vars.email_id }}"
      - meta: end_play
  - name: Getting the device details information of storage group
    block:
      - name: Getting the device details information of storage group
        uri:
          url: "{{ ansible_local.playbook_vars.unisphere_url }}/univmax/restapi/90/sloprovisioning/symmetrix/{{ ansible_local.playbook_vars.symmetrixId }}/volume?volume_identifier={{ ansible_local.playbook_vars.Ticket }}&storageGroupId={{ ansible_local.playbook_vars.storageGroupId }}"
          method: GET
          validate_certs: no
          user: "{{ ansible_local.playbook_vars.Username }}"
          password: "{{ ansible_local.playbook_vars.Password }}"
          force_basic_auth: yes
          status_code: 201,200
        register: volume_details
      - name: list of wwn
        debug:
          msg: "{{ volume_details.json.resultList.result|map(attribute='volumeId')|list }}"
    rescue:
      - debug:
          msg: 'I caught an error'
      - shell: echo -e "Hi Team  \n\nTask- Getting the device details information of storage group- FAILED \n\nRegards" | mailx  -s "Update on ticket {{ ansible_local.playbook_vars.Ticket }}" -S smtp="{{ ansible_local.playbook_vars.smtp_server }}" "{{ ansible_local.playbook_vars.email_id }}"
      - meta: end_play
